<section class="mt-3 card card-body">
    <h1>Nova Categoria</h1>

    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="categoria">Nome</label>
                <input name="categoria" type="text" id="categoria" class="form-control mb-3">

                <button class="btn btn-primary">Pronto</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</section>