<section class="card card-body">
    <h1>Novo curso</h1>

    <div class="row ">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input name="nome" type="text" id="nome" class="form-control mb-3">
                <label for="cargaHoraria">Carga horaria</label>
                <input name="cargaHoraria" type="number" id="cargaHoraria" class="form-control mb-3">
                <label for="descricao">Descrição</label>
                <input name="descricao" type="text" id="descricao" class="form-control mb-3">
                <label for="categoria">Categoria</label>

                <select name="categoria" class="form-control mb-3">
                <option disabled selected>-- Selecione --</option>
                    <?php
                        foreach($categorias as $categoria){
                            echo "
                                <option value='{$categoria->id}'>{$categoria->nome}</option>
                            ";
                        }
                    ?>
                </select>
                
                <button class="btn btn-outline-dark w-100">Enviar</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</section>